name = "cf-workers-webssh"
main = "src/worker.ts"
compatibility_date = "2026-07-01"
workers_dev = true

[build]
command = "npm run build:web"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true

[vars]
CONNECT_TIMEOUT_MS = "10000"

[[durable_objects.bindings]]
name = "SSH_SESSIONS"
class_name = "SSHSessionDO"

[[kv_namespaces]]
binding = "CONNECTIONS_KV"
id = "94ed95f4d6614aecbc1f717b36e16712"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SSHSessionDO"]
